version: '3'

services:
  spring:
    build:
      context: ./java_server
      dockerfile: Dockerfile
    ports:
      - '8085:8080'
    restart: always
    networks:
      - epitome
    volumes:
      - ./music:/app/static/music

  flask:
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    restart: always
    networks:
      - epitome

networks:
  epitome:
